# Generated by Django 2.2.5 on 2019-09-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.TextField(max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
