# Generated by Django 2.2.5 on 2019-09-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190912_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.TextField(unique=True, verbose_name='Название'),
        ),
    ]
