# Generated by Django 2.2.5 on 2019-09-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_submenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('url_alias', models.CharField(max_length=64, unique=True, verbose_name='Url адрес')),
                ('meta_keywords', models.TextField(max_length=255, verbose_name='meta keywords')),
                ('meta_description', models.TextField(max_length=255, verbose_name='meta description')),
                ('image', models.ImageField(upload_to='./images/category', verbose_name='Изображение')),
            ],
        ),
    ]
