# Generated by Django 2.2.5 on 2019-09-13 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190913_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('long_description', models.TextField(max_length=500, verbose_name='Описание')),
                ('short_description', models.TextField(max_length=255, verbose_name='Сниппет')),
                ('meta_keywords', models.TextField(max_length=255, verbose_name='meta keywords')),
                ('meta_description', models.TextField(max_length=255, verbose_name='meta description')),
                ('image', models.ImageField(upload_to='./catalog', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.Category')),
            ],
        ),
    ]
