# Generated by Django 2.2.5 on 2019-09-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190914_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumb_image',
            field=models.ImageField(blank=True, upload_to='./catalog/thumb', verbose_name='Маленькое изображение'),
        ),
    ]
