# Generated by Django 2.2.5 on 2019-09-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190915_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='compressed_image',
            field=models.ImageField(blank=True, upload_to='./category', verbose_name='Изображение'),
        ),
    ]
