# Generated by Django 2.2.5 on 2019-09-17 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190917_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderblock',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='api.Block'),
        ),
        migrations.CreateModel(
            name='BannerBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='banner', max_length=20, verbose_name='Тип')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('align_button', models.IntegerField(choices=[(1, 'left'), (2, 'center'), (3, 'right')], verbose_name='Выравнивание кнопки')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='api.Block')),
            ],
        ),
    ]
