# Generated by Django 2.2.5 on 2019-09-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190917_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerblock',
            name='compressed_image',
            field=models.ImageField(blank=True, upload_to='./banner', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='bannerblock',
            name='image',
            field=models.ImageField(default=1, upload_to='./banner', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
