# Generated by Django 2.2.5 on 2019-09-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190917_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerblock',
            name='button_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст кнопки'),
            preserve_default=False,
        ),
    ]
