# Generated by Django 2.2.5 on 2019-09-21 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190920_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Option'),
            preserve_default=False,
        ),
    ]
