# Generated by Django 2.2.5 on 2019-09-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_image_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Option'),
        ),
    ]
