# Generated by Django 2.2.5 on 2019-09-21 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190921_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerblock',
            name='align_button',
        ),
        migrations.AddField(
            model_name='bannerblock',
            name='align_button_horisontal',
            field=models.IntegerField(choices=[(1, 'left'), (2, 'center'), (3, 'right')], default=1, verbose_name='Выравнивание кнопки по горизонтали'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannerblock',
            name='align_button_vertical',
            field=models.IntegerField(choices=[(1, 'top'), (2, 'center'), (3, 'bottom')], default=1, verbose_name='Выравнивание кнопки по вертикали'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannerblock',
            name='align_text_horisontal',
            field=models.IntegerField(choices=[(1, 'left'), (2, 'center'), (3, 'right')], default=1, verbose_name='Выравнивание текста по горизонтали'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannerblock',
            name='align_text_vertical',
            field=models.IntegerField(choices=[(1, 'top'), (2, 'center'), (3, 'bottom')], default=1, verbose_name='Выравнивание текста по вертикали'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannerblock',
            name='is_full',
            field=models.BooleanField(default=False, verbose_name='На весь экран'),
        ),
        migrations.AddField(
            model_name='bannerblock',
            name='text_size',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(16)], verbose_name='Размер текста'),
        ),
    ]
