# Generated by Django 2.2.5 on 2019-09-23 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20190921_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerblock',
            name='text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bannerblock',
            name='text_size',
            field=models.IntegerField(default=40, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(30)], verbose_name='Размер текста'),
        ),
    ]
