# Generated by Django 2.2.5 on 2019-09-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190923_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
