# Generated by Django 2.2.5 on 2019-09-30 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
