# Generated by Django 2.2.5 on 2019-10-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'manager'), (3, 'customer')], default=1, verbose_name='Роль'),
        ),
    ]
